### ISSUE TITLE
Rename `python-version` to `env-python-version`, make its default value `auto`

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/ansible-test-gh-action#18]
Right now `python-version` is called "controller Python version", which in the context of integration tests is plainly wrong since it is **not** the Python version used for the controller container, but the Python version used to install ansible-core and launch ansible-test in. ansible-test in turn starts one or two containers (depending on the Python versions supported by the target image, an additional `default` container will be started to run the controller part of the tests in).

To avoid such confusion this Python version should better be called "environment Python version", and denoted by `env-python-version` (or something like that, bikeshed if you want...).

Also there should be a value `auto` for this option, which selects some (preferably the latest) supported version of Python for the ansible-core version selected. This would be 3.8 for Ansible 2.9, 3.9 for ansible-base 2.10 and ansible-core 2.11, 3.10 for ansible-core 2.12 and 2.13.

**Comment by webknjaz** [comment]
I'd like to invite @mattclay to decide on the naming because ultimately everyone would benefit from having the internal ansible-core naming aligned with the action ones.

So the proposal summary is this API:
```yaml
- uses: ansible-community/ansible-test-gh-action@release/v2
  with:
    ...
    gha-worker-env-python-version: auto  # naming this is hard
    controller-python-version: auto
    target-python-version: auto
```
