### ISSUE TITLE
Integration tests are failing with "ls: cannot access '/tests/output/reports/coverage=integration.xml': No such file or directory"

### ISSUE THREAD

**Issue by griffinfujioka** [ansible-community/ansible-test-gh-action#67]
I am developing an ansible collection and I am able to run the integration tests locally with: `ansible-test integration --docker default -v`

However, my Github Action is failing with `ls: cannot access '/tests/output/reports/coverage=integration.xml': No such file or directory`. 

Here is the way I'm using the action: 

```
  integration:
    # The integration tests need to run on a self-hosted Github Actions runner because the tests access internal components which only allow internal traffic 
    runs-on: [self-hosted, build]
    strategy:
      # As soon as the first integration test fails, cancel the others to free up the CI queue
      fail-fast: true
      matrix:
        ansible:
          - stable-2.9 # Only if your collection supports Ansible 2.9
          - stable-2.10 # Only if your collection supports ansible-base 2.10
          - stable-2.11 # Only if your collection supports ansible-core 2.11
          - stable-2.12
          - stable-2.13
          - stable-2.14
          - stable-2.15

    steps:
      - name: >-
          Perform integration testing against
          Ansible version ${{ matrix.ansible }}
        # See the documentation for the following GitHub action on
        # https://github.com/ansible-community/ansible-test-gh-action/blob/main/README.md
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: integration
          coverage: never
          integration-diff: false
```
